#!/usr/bin/env bash

set -e

GH_CLONE_DIR=${GH_CLONE_DIR:=${HOME}/Workspace/github.com}

help(){
  echo
  echo "Usage: ${0##*/} [OWNER]/REPO"
  echo
  echo "Clone a GitHub repository and optionally open in an editor."
  echo
  echo "Optional environment variables to customize behavior:"
  echo
  echo "  GH_CLONE_DIR      Directory to clone repositories into (default: ${HOME}/Workspace/github.com)"
  echo "  GH_CLONE_EDITOR   Editor to use for opening the cloned repository"
  echo
  exit 1
}

## check for required arguments
if [ -z "$1" ]; then
  help
fi

## exit if overriding git protocol configuration
if [[ $1 = https://* ]] || [[ $1 = git@* ]]; then
  echo "error: overriding git protocol configuration unsupported"
  help
fi

OWNER=${1%%/*}
REPO=${1##*/}

## get authenticated user when specifying `OWNER/` is omitted
if [ ${#1} = ${#OWNER} ]; then
  OWNER=$(gh api user --jq .login)
fi

## clone or sync
if [ -d "$GH_CLONE_DIR/$OWNER/$REPO" ]; then
  echo "repository clone exists, syncing instead..."
  echo
  cd "$GH_CLONE_DIR/$OWNER/$REPO" && gh repo sync
else
  gh repo clone "$OWNER/$REPO" "$GH_CLONE_DIR/$OWNER/$REPO"
fi

## optionally open cloned repo in editor
if [ -n "$GH_CLONE_EDITOR" ]; then
   echo "opening repository in editor..."
   command "${GH_CLONE_EDITOR}" "$GH_CLONE_DIR/$OWNER/$REPO"
fi